// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/svc.proto

package grpctest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeaderPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HeaderPair) Reset() {
	*x = HeaderPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_svc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderPair) ProtoMessage() {}

func (x *HeaderPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_svc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderPair.ProtoReflect.Descriptor instead.
func (*HeaderPair) Descriptor() ([]byte, []int) {
	return file_proto_svc_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderPair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HeaderPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type HeadersAndFirstChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionID string        `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	RemoteAddr    string        `protobuf:"bytes,2,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	ConfigID      string        `protobuf:"bytes,3,opt,name=configID,proto3" json:"configID,omitempty"`
	Method        string        `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Uri           string        `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	UriParsed     []byte        `protobuf:"bytes,6,opt,name=uriParsed,proto3" json:"uriParsed,omitempty"`
	Protocol      string        `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	QueryString   string        `protobuf:"bytes,8,opt,name=queryString,proto3" json:"queryString,omitempty"`
	ProtoNum      string        `protobuf:"bytes,9,opt,name=protoNum,proto3" json:"protoNum,omitempty"`
	RequestLine   string        `protobuf:"bytes,10,opt,name=requestLine,proto3" json:"requestLine,omitempty"`
	FileName      string        `protobuf:"bytes,11,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Headers       []*HeaderPair `protobuf:"bytes,12,rep,name=headers,proto3" json:"headers,omitempty"`
}

func (x *HeadersAndFirstChunk) Reset() {
	*x = HeadersAndFirstChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_svc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeadersAndFirstChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadersAndFirstChunk) ProtoMessage() {}

func (x *HeadersAndFirstChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_svc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadersAndFirstChunk.ProtoReflect.Descriptor instead.
func (*HeadersAndFirstChunk) Descriptor() ([]byte, []int) {
	return file_proto_svc_proto_rawDescGZIP(), []int{1}
}

func (x *HeadersAndFirstChunk) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

func (x *HeadersAndFirstChunk) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *HeadersAndFirstChunk) GetConfigID() string {
	if x != nil {
		return x.ConfigID
	}
	return ""
}

func (x *HeadersAndFirstChunk) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HeadersAndFirstChunk) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *HeadersAndFirstChunk) GetUriParsed() []byte {
	if x != nil {
		return x.UriParsed
	}
	return nil
}

func (x *HeadersAndFirstChunk) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *HeadersAndFirstChunk) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

func (x *HeadersAndFirstChunk) GetProtoNum() string {
	if x != nil {
		return x.ProtoNum
	}
	return ""
}

func (x *HeadersAndFirstChunk) GetRequestLine() string {
	if x != nil {
		return x.RequestLine
	}
	return ""
}

func (x *HeadersAndFirstChunk) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *HeadersAndFirstChunk) GetHeaders() []*HeaderPair {
	if x != nil {
		return x.Headers
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Something string `protobuf:"bytes,1,opt,name=something,proto3" json:"something,omitempty"`
	Else      string `protobuf:"bytes,2,opt,name=else,proto3" json:"else,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_svc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_svc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_svc_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetSomething() string {
	if x != nil {
		return x.Something
	}
	return ""
}

func (x *Response) GetElse() string {
	if x != nil {
		return x.Else
	}
	return ""
}

var File_proto_svc_proto protoreflect.FileDescriptor

var file_proto_svc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x67, 0x72, 0x70, 0x63, 0x74, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x0a, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x88, 0x03, 0x0a, 0x14, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x41, 0x6e, 0x64,
	0x46, 0x69, 0x72, 0x73, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x72, 0x69, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x75, 0x72, 0x69, 0x50, 0x61,
	0x72, 0x73, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x20, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x4e, 0x75, 0x6d, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x4e, 0x75, 0x6d, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x07,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50,
	0x61, 0x69, 0x72, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x22, 0x3c, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x6d, 0x65,
	0x74, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x6d,
	0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x6c, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x6c, 0x73, 0x65, 0x32, 0x45, 0x0a, 0x05, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x3c, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x1e, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x41, 0x6e,
	0x64, 0x46, 0x69, 0x72, 0x73, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x12, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x74, 0x65, 0x73, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_svc_proto_rawDescOnce sync.Once
	file_proto_svc_proto_rawDescData = file_proto_svc_proto_rawDesc
)

func file_proto_svc_proto_rawDescGZIP() []byte {
	file_proto_svc_proto_rawDescOnce.Do(func() {
		file_proto_svc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_svc_proto_rawDescData)
	})
	return file_proto_svc_proto_rawDescData
}

var file_proto_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_svc_proto_goTypes = []interface{}{
	(*HeaderPair)(nil),           // 0: grpctest.HeaderPair
	(*HeadersAndFirstChunk)(nil), // 1: grpctest.HeadersAndFirstChunk
	(*Response)(nil),             // 2: grpctest.Response
}
var file_proto_svc_proto_depIdxs = []int32{
	0, // 0: grpctest.HeadersAndFirstChunk.headers:type_name -> grpctest.HeaderPair
	1, // 1: grpctest.Hello.Echo:input_type -> grpctest.HeadersAndFirstChunk
	2, // 2: grpctest.Hello.Echo:output_type -> grpctest.Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_svc_proto_init() }
func file_proto_svc_proto_init() {
	if File_proto_svc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_svc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_svc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeadersAndFirstChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_svc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_svc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_svc_proto_goTypes,
		DependencyIndexes: file_proto_svc_proto_depIdxs,
		MessageInfos:      file_proto_svc_proto_msgTypes,
	}.Build()
	File_proto_svc_proto = out.File
	file_proto_svc_proto_rawDesc = nil
	file_proto_svc_proto_goTypes = nil
	file_proto_svc_proto_depIdxs = nil
}
